import categories from '../Page/CreatePost/categoryData'

const array = [
    {
        categoryId: 1,
        subCategories: [
            // Apartment
            {
                subCategoryId: 13,
                canBan: null,
                chuaBanGiao: null,
                tenDuAn: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',

                maCan: '',
                block: '',
                tangSo: '',
                loaiHinh: '',
                soPhongNgu: '',
                soToilet: '',
                ccBanCong: '',
                ccHuongCuaChinh: '',
                ccGiayToPhapLy: '',
                ccTinhTrangNoiThat: '',
                dienTich: '',
                gia: '',
                soTienCoc: '',
                caNhan: null,
            },
            // House
            {
                subCategoryId: 14,
                canBan: null,
                chuaBanGiao: null,
                tenDuAn: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',

                soTang: '',
                nhaOLoaiHinh: '',
                nhaOSoPhongNgu: '',
                nhaOHuongCuaChinh: '',
                nhaOSoPhongVeSinh: '',
                nhaOGiayToPhapLy: '',
                nhaOTinhTrangNoiThat: '',
                nhaOhemXeHoi: false,
                nhaOnoHau: false,
                dienTich: '',
                dienTichSuDung: '',
                nhaOchieuNgang: '',
                nhaOchieuDai: '',
                gia: '',
                soTienCoc: '',
                caNhan: null,
            },
            // Land
            {
                subCategoryId: 15,
                canBan: null,
                tenDuAn: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',

                datMatTien: false,
                datLoaiHinhDat: '',
                datHuongDat: '',
                datGiayToPhapLy: '',
                datHemXeHoi: false,
                datNoHau: false,
                dienTich: '',
                datChieuNgang: '',
                datChieuDai: '',
                gia: '',
                soTienCoc: '',
                caNhan: null,
            },
            // Office
            {
                subCategoryId: 16,
                canBan: null,
                tenDuAn: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',

                vanPhongTangSo: '',
                vanPhongLoaiHinhVanPhong: '',
                vanPhongHuongCuaChinh: '',
                vanPhongGiayToPhapLy: '',
                vanPhongTinhTrangNoiThat: '',
                dienTich: '',
                gia: '',
                soTienCoc: '',
                caNhan: null,
            },
            // Motel
            {
                subCategoryId: 17,
                tenDuAn: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',

                phongTroTinhTrangNoiThat: '',
                dienTich: '',
                gia: '',
                phongTroSoTienCoc: '',
                caNhan: null,
            },
        ],
    },
    {
        categoryId: 2,
        subCategories: [
            {
                subCategoryId: 18,
                hangXe: '',
                otoDongXe: '',
                nam: '',
                xuatxu: '',
                bienSoXe: '',
                soKmDaDi: '',
                daSuDung: true,
                mauSac: '',
                otoHopSo: '',
                otoNhieuLieu: '',
                otoKieuDang: '',
                otoSocho: '',
                gia: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 20,
                hangXe: '',
                nam: '',
                xuatxu: '',
                bienSoXe: '',
                soKmDaDi: '',
                daSuDung: true,
                gia: '',
                mauSac: '',
                xeTaiTrongTai: '',
                xeTaiNhieuLieu: '',
                xeTaiXuatXu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 19,
                hangXe: '',
                xeMayDongXe: '',
                nam: '',
                mauSac: '',
                xuatxu: '',
                bienSoXe: '',
                soKmDaDi: '',
                daSuDung: true,
                xeMayDungtich: '',
                xeMayLoaiXe: '',
                gia: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 21,
                hangXe: '',
                nam: '',
                xuatxu: '',
                xeDienDaSuDung: true,
                gia: '',
                mauSac: '',
                xeDienLoaiXe: '',
                xeDienDongCo: '',
                xeDienBaoHanh: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 22,
                hangXe: '',
                nam: '',
                xuatxu: '',
                gia: '',
                mauSac: '',
                xeDapDaSuDung: true,
                xeDapLoaiXe: '',
                xeDapKichThuocKhung: '',
                xeDapChatLuongKhung: '',
                xeDapBaoHang: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 23,
                hangXe: '',
                nam: '',
                xuatxu: '',
                gia: '',
                mauSac: '',
                bienSoXe: '',
                soKmDaDi: '',
                phuongTienDaSuDung: '',
                phuongTienKhacLoaiXe: '',
                phuongTienKhacDongXe: '',
                phuongTienKhacSoCho: '',
                phuongTienKhacSuDung: true,
                phuongTienKhacNhienLieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 24,
                gia: '',
                phuTungXeLoaiPhuTung: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    {
        categoryId: 3,
        subCategories: [
            {
                subCategoryId: 25,
                gia: '',
                dienThoaiHang: '',
                dienThoaiDongMay: '',
                dienThoaiMauSac: '',
                dienThoaiDungLuong: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                phienBan: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // Tablet
            {
                subCategoryId: 26,
                gia: '',
                mayTinhBangHang: '',
                mayTinhBangDongMay: '',
                mayTinhBangDungLuong: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                mayTinhBangQuocTe: false,
                mayTinhBang4g: '',
                mayTinhBangKichCoManHinh: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // Laptop
            {
                subCategoryId: 27,
                gia: '',
                laptopHang: '',
                laptopDongMay: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                laptopBoViXuly: '',
                laptopRam: '',
                laptopOcung: '',
                laptopHdd: '',
                laptopCardManHinh: '',
                laptopKichCoManHinh: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // Desktop
            {
                subCategoryId: 28,
                gia: '',
                tinhTrang: '',
                baoHanh: '',
                mayTinhDeBanMienPhi: false,
                mayTinhDeBanBoViXuly: '',
                mayTinhDeBanRam: '',
                mayTinhDeBanOcung: '',
                mayTinhDeBanHdd: '',
                mayTinhDeBanCardManHinh: '',
                mayTinhDeBanKichCoManHinh: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // camera
            {
                subCategoryId: 29,
                gia: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                mayAnhThietBi: '',
                thietBiDongMay: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // Smart device
            {
                subCategoryId: 31,
                gia: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                thietBiDeoThongMinhThietBi: '',
                thietBiDeoThongMinhHang: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // phu kien
            {
                subCategoryId: 32,
                gia: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                phuKienLoaiPhuKien: '',
                phuKienThietBi: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // linh kiện
            {
                subCategoryId: 33,
                gia: '',
                tinhTrang: '',
                baoHanh: '',
                mienPhi: false,
                linhKienLoaiPhuKien: '',
                linhKienThietBi: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    // Việc làm
    {
        categoryId: 4,
        tinhTrang: '',
        caNhan: false,
        tenHoKinhDoanh: '',
        soLuongTuyenDung: '',
        nganhNghe: '',
        loaiCongViec: '',
        hinhThucTraLuong: '',
        luongToiThieu: '',
        luongToiDa: '',
        doTuoiToiThieu: '',
        doTuoiToiDa: '',
        nam: false,
        hocVanToiThieu: '',
        kinhNghiem: '',
        chungChi: '',
        quyenLoi: '',
        address: {
            thanhPho: '',
            quanHuyen: '',
            phuongXa: '',
            tenDuong: '',
            soNha: '',
        },
    },
    {
        categoryId: 5,
        subCategories: [
            {
                subCategoryId: 34,
                mienPhi: false,
                gia: '',
                giongThuCung: '',
                doTuoi: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 35,
                mienPhi: false,
                gia: '',
                giongThuCung: '',
                doTuoi: '',
                choKichCo: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 36,
                mienPhi: false,
                gia: '',
                giongThuCung: '',
                doTuoi: '',
                chimGioiTinh: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 37,
                mienPhi: false,
                gia: '',
                giongThuCung: '',
                doTuoi: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 38,
                mienPhi: false,
                gia: '',
                giongThuCung: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    {
        categoryId: 6,
        mienPhi: false,
        gia: '',
        loaiThucPham: '',
        address: {
            thanhPho: '',
            quanHuyen: '',
            phuongXa: '',
            tenDuong: '',
            soNha: '',
        },
    },
    {
        categoryId: 7,
        subCategories: [
            {
                subCategoryId: 40,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                tuLanhTheTich: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 41,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                mayLanhCongSuat: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 42,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                mayGiatCuaMayGiat: '',
                mayGiatKhoiLuongGiat: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    {
        categoryId: 8,
        subCategories: [
            // bàn ghế
            {
                subCategoryId: 43,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                banGheChatLieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // tủ kệ
            {
                subCategoryId: 44,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                tuKeChatLieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // giường
            {
                subCategoryId: 45,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                giuongChatLieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // bếp
            {
                subCategoryId: 46,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                bepThuongHieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // dụng cụ bếp
            {
                subCategoryId: 47,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // quạt
            {
                subCategoryId: 48,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                quatThuongHieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // Đèn
            {
                subCategoryId: 49,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // cây
            {
                subCategoryId: 50,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // vệ sinh
            {
                subCategoryId: 51,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thietBiVeSinhThuongHieu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 52,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    {
        categoryId: 9,
        mienPhi: false,
        gia: '',
        hang: '',
        daSuDung: false,
        loaiSanPham: '',
        address: {
            thanhPho: '',
            quanHuyen: '',
            phuongXa: '',
            tenDuong: '',
            soNha: '',
        },
    },
    {
        categoryId: 10,
        subCategories: [
            // quần áo
            {
                subCategoryId: 53,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // đồng hồ
            {
                subCategoryId: 54,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // giày dép
            {
                subCategoryId: 55,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // túi xách
            {
                subCategoryId: 56,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // nước hoa
            {
                subCategoryId: 57,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // phụ kiện
            {
                subCategoryId: 58,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                loaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    {
        categoryId: 11,
        subCategories: [
            // nhạc cụ
            {
                subCategoryId: 59,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                nhacCuLoaiNhacCu: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // sách
            {
                subCategoryId: 60,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // đồ thể thao
            {
                subCategoryId: 61,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // đồ sưu tầm
            {
                subCategoryId: 62,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                doSuuTamLoaiSanPham: '',
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // game
            {
                subCategoryId: 63,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            // khác
            {
                subCategoryId: 64,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
    {
        categoryId: 12,
        subCategories: [
            {
                subCategoryId: 65,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
            {
                subCategoryId: 66,
                mienPhi: false,
                gia: '',
                hang: '',
                daSuDung: false,
                thanhPho: '',
                quanHuyen: '',
                phuongXa: '',
                diaChiCuThe: '',
            },
        ],
    },
]

export const generateDefaultValueFormData = (id, subCategoryId) => {
    let defaultFormData = {
        title: '',
        description: '',
        medias: [],
    }
    console.log(id)
    array.forEach(({ categoryId, subCategories }) => {
        if (id === categoryId) {
            defaultFormData.categoryId = id
            if (!subCategoryId) {
                const form = array.find(item => item.categoryId === categoryId)
                defaultFormData = {
                    ...defaultFormData,
                    ...form,
                    title: '',
                    description: '',
                    medias: [],
                    address: {
                        thanhPho: '',
                        quanHuyen: '',
                        phuongXa: '',
                        tenDuong: '',
                        soNha: '',
                    },
                }
            } else {
                subCategories.forEach(subCategory => {
                    if (subCategory.subCategoryId === subCategoryId) {
                        defaultFormData = {
                            ...defaultFormData,
                            ...subCategory,
                        }
                    }
                })
            }
        }
    })

    return defaultFormData
}

export function convertFile(file, callback) {
    const reader = new FileReader() //this for convert to Base64
    reader.readAsDataURL(file) //start conversion...

    reader.onload = function (e) {
        //.. once finished..
        const rawLog = reader.result.split(',')[1] //extract only thee file data part
        const dataSend = {
            dataReq: { data: rawLog, name: file.name, type: file.type },
            fname: 'uploadFilesToGoogleDrive',
        } //preapre info to send to API
        callback({ type: file.type, fileData: dataSend })
    }
}

export const uploadImage = async files => {
    const fileIdArray = await Promise.all(
        files.map(async ({ type, fileData, id }) => {
            if (!fileData) {
                return new Promise(resolve => {
                    resolve({ type, id })
                })
            }
            const res = await fetch(
                'https://script.google.com/macros/s/AKfycbwXhX4N82ic3vhrVOK493pjOfR9-pISPf7jsSmpiBcf_IHuQCc/exec',
                { method: 'POST', body: JSON.stringify(fileData) }
            )
            const data = await res.json()
            return { type, id: data.id }
        })
    )
    return fileIdArray
}

export const getCategory = categoryId =>
    categories.find(({ id }) => id === categoryId)

export const getSubCategory = (categoryId, subCategoryId) => {
    const category = getCategory(categoryId)
    if (!category) {
        return
    } else if (category.subCategory === null) {
        return null
    }
    return category.subCategory.find(({ id }) => subCategoryId === id)
}
