// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STU.LVTN.SERVER.Model;

#nullable disable

namespace STU.LVTN.SERVER.Migrations
{
    [DbContext(typeof(LVTNContext))]
    [Migration("20220518092253_addMissingFieldIntoBaiDangXeCo")]
    partial class addMissingFieldIntoBaiDangXeCo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangBatDongSanEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    b.Property<bool?>("CanBan")
                        .HasColumnType("bit");

                    b.Property<string>("CcBanCong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcBlock")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CC_Block")
                        .IsFixedLength();

                    b.Property<bool?>("CcChuaBanGiao")
                        .HasColumnType("bit")
                        .HasColumnName("CC_ChuaBanGiao");

                    b.Property<string>("CcGiayToPhapLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcHuongCuaChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcLoaiHinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CC_LoaiHinh");

                    b.Property<string>("CcMaCan")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CC_MaCan")
                        .IsFixedLength();

                    b.Property<byte?>("CcSoPhongNgu")
                        .HasColumnType("tinyint")
                        .HasColumnName("CC_SoPhongNgu");

                    b.Property<string>("CcTangSo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CC_TangSo")
                        .IsFixedLength();

                    b.Property<string>("CcTinhTrangNoiThat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DatChieuDai")
                        .HasColumnType("float")
                        .HasColumnName("Dat_ChieuDai");

                    b.Property<double?>("DatChieuNgang")
                        .HasColumnType("float")
                        .HasColumnName("Dat_ChieuNgang");

                    b.Property<bool?>("DatHemXeHoi")
                        .HasColumnType("bit")
                        .HasColumnName("Dat_HemXeHoi");

                    b.Property<string>("DatHuongDat")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Dat_HuongDat");

                    b.Property<string>("DatLoaiHinhDat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dat_LoaiHinhDat");

                    b.Property<bool?>("DatMatTien")
                        .HasColumnType("bit")
                        .HasColumnName("Dat_MatTien");

                    b.Property<bool?>("DatNoHau")
                        .HasColumnType("bit")
                        .HasColumnName("Dat_NoHau");

                    b.Property<double?>("DienTich")
                        .HasColumnType("float");

                    b.Property<double?>("NhaOChieuDai")
                        .HasColumnType("float")
                        .HasColumnName("NhaO_ChieuDai");

                    b.Property<double?>("NhaOChieuNgang")
                        .HasColumnType("float")
                        .HasColumnName("NhaO_ChieuNgang");

                    b.Property<bool?>("NhaOHemXeHoi")
                        .HasColumnType("bit")
                        .HasColumnName("NhaO_HemXeHoi");

                    b.Property<string>("NhaOLoaiHinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhaO_LoaiHinh");

                    b.Property<bool?>("NhaONoHau")
                        .HasColumnType("bit")
                        .HasColumnName("NhaO_NoHau");

                    b.Property<byte?>("NhaOSoPhongNgu")
                        .HasColumnType("tinyint")
                        .HasColumnName("NhaO_SoPhongNgu");

                    b.Property<byte?>("NhaOSoPhongVeSinh")
                        .HasColumnType("tinyint")
                        .HasColumnName("NhaO_SoPhongVeSinh");

                    b.Property<byte?>("NhaOTongSoTang")
                        .HasColumnType("tinyint")
                        .HasColumnName("NhaO_TongSoTang");

                    b.Property<double?>("PhongTroSoTienCoc")
                        .HasColumnType("float")
                        .HasColumnName("PhongTro_SoTienCoc");

                    b.Property<string>("PhongTroTinhTrangNoiThat")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("PhongTro_TinhTrangNoiThat");

                    b.Property<float?>("SoTienCoc")
                        .HasColumnType("real");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VanPhongBlock")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("VanPhong_Block")
                        .IsFixedLength();

                    b.Property<string>("VanPhongLoaiHinhVanPhong")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("VanPhong_LoaiHinhVanPhong");

                    b.Property<string>("VanPhongMaCan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VanPhong_MaCan");

                    b.Property<string>("VanPhongTangSo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("VanPhong_TangSo")
                        .IsFixedLength();

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_BatDongSan", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangDoAnThucPhamEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<string>("LoaiThucPham")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_DoAnThucPham", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangDoDienTuEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool?>("BaoHanh")
                        .HasColumnType("bit");

                    b.Property<string>("DienThoaiDungLuong")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DienThoai_DungLuong");

                    b.Property<string>("DienThoaiHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DienThoai_Hang");

                    b.Property<string>("DienThoaiMauSac")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DienThoai_MauSac");

                    b.Property<string>("LaptopBoViXuly")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Laptop_BoViXuly");

                    b.Property<string>("LaptopCardManHinh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("Laptop_CardManHinh")
                        .IsFixedLength();

                    b.Property<string>("LaptopHang")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("Laptop_Hang")
                        .IsFixedLength();

                    b.Property<bool?>("LaptopHdd")
                        .HasColumnType("bit")
                        .HasColumnName("Laptop_HDD");

                    b.Property<string>("LaptopKichCoManHinh")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("Laptop_KichCoManHinh")
                        .IsFixedLength();

                    b.Property<string>("LaptopOcung")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Laptop_OCung");

                    b.Property<string>("LaptopRam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Laptop_RAM");

                    b.Property<string>("LinhKienLoaiPhuKien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LinhKien_LoaiPhuKien");

                    b.Property<string>("LinhKienThietBi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("LinhKien_ThietBi");

                    b.Property<string>("LinhKienTinhTrang")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("LinhKien_TinhTrang");

                    b.Property<string>("MayAnhThietBi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MayAnh_ThietBi");

                    b.Property<string>("MayAnhTinhTrang")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("MayAnh_TinhTrang");

                    b.Property<bool?>("MayTinhBang4g")
                        .HasColumnType("bit")
                        .HasColumnName("MayTinhBang_4g");

                    b.Property<string>("MayTinhBangDungLuong")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("MayTinhBang_DungLuong");

                    b.Property<bool?>("MayTinhBangQuocTe")
                        .HasColumnType("bit")
                        .HasColumnName("MayTinhBang_QuocTe");

                    b.Property<string>("MayTinhDeBanBoViXuly")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("MayTinhDeBan_BoViXuly");

                    b.Property<string>("MayTinhDeBanCardManHinh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MayTinhDeBan_CardManHinh")
                        .IsFixedLength();

                    b.Property<bool?>("MayTinhDeBanHdd")
                        .HasColumnType("bit")
                        .HasColumnName("MayTinhDeBan_HDD");

                    b.Property<string>("MayTinhDeBanKichCoManHinh")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("MayTinhDeBan_KichCoManHinh")
                        .IsFixedLength();

                    b.Property<string>("MayTinhDeBanOcung")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MayTinhDeBan_OCung");

                    b.Property<string>("MayTinhDeBanRam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MayTinhDeBan_RAM");

                    b.Property<string>("PhuKienLoaiPhuKien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuKien_LoaiPhuKien");

                    b.Property<string>("PhuKienThietBi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PhuKien_ThietBi");

                    b.Property<string>("PhuKienTinhTrang")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PhuKien_TinhTrang");

                    b.Property<string>("ThietBiDeoThongMinhHang")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ThietBiDeoThongMinh_Hang");

                    b.Property<string>("ThietBiDeoThongMinhThietBi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ThietBiDeoThongMinh_ThietBi");

                    b.Property<string>("ThietBiDeoThongMinhTinhTrang")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ThietBiDeoThongMinh_TinhTrang");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiviThietBi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tivi_ThietBi");

                    b.Property<string>("TiviTinhTrang")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Tivi_TinhTrang");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_DoDienTu", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangDoDungVanPhongEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_DoDungVanPhong", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangDoGiaDungEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<string>("BanGheChatLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BanGhe_ChatLieu");

                    b.Property<string>("BepThuongHieu")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("Bep_ThuongHieu");

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("GiuongChatLieu")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Giuong_ChatLieu");

                    b.Property<string>("LoaiSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuatThuongHieu")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("Quat_ThuongHieu");

                    b.Property<string>("ThietBiVeSinhThuongHieu")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("ThietBiVeSinh_ThuongHieu");

                    b.Property<string>("TuKeChatLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TuKe_ChatLieu");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_DoGiaDung", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool>("AnTin")
                        .HasColumnType("bit");

                    b.Property<bool?>("CaNhan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiCuThe")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<int?>("IdBaiDangChiTiet")
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDangChiTiet");

                    b.Property<int>("IdDanhMucCha")
                        .HasColumnType("int")
                        .HasColumnName("id_DanhMucCha");

                    b.Property<int?>("IdDanhMucCon")
                        .HasColumnType("int")
                        .HasColumnName("id_DanhMucCon");

                    b.Property<bool?>("MienPhi")
                        .HasColumnType("bit");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SdtNguoiBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sdt_NguoiBan");

                    b.Property<string>("SdtNguoiMua")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sdt_NguoiMua");

                    b.Property<string>("TablesDetail")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdBaiDang");

                    b.HasIndex("IdDanhMucCon");

                    b.HasIndex("SdtNguoiBan");

                    b.ToTable("BaiDang", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangGiaiTriEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("DoSuuTamLoaiSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DoSuuTam_LoaiSanPham");

                    b.Property<bool?>("MienPhi")
                        .HasColumnType("bit");

                    b.Property<string>("NhacCuLoaiNhacCu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NhacCu_LoaiNhacCu");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_GiaiTri", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangMeVaBeEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_MeVaBe", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangThoiTrangEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_ThoiTrang", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangThuCungEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<string>("ChimGioiTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Chim_GioiTinh");

                    b.Property<string>("ChoKichCo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Cho_KichCo");

                    b.Property<string>("DoTuoi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GiongThuCung")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_ThuCung", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangTuLanhEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("Hang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MayGiatCuaMayGiat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MayGiat_CuaMayGiat");

                    b.Property<string>("MayGiatKhoiLuongGiat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MayGiat_KhoiLuongGiat");

                    b.Property<string>("MayLanhCongSuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MayLanh_CongSuat");

                    b.Property<string>("TuLanhTheTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TuLanh_TheTich");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_TuLanh", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangViecLamEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<string>("ChungChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhThucTraLuong")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("HocVanToiThieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiCongViec")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("LuongToiDa")
                        .HasColumnType("float");

                    b.Property<double?>("LuongToiThieu")
                        .HasColumnType("float");

                    b.Property<bool?>("Nam")
                        .HasColumnType("bit");

                    b.Property<string>("NganhNghe")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QuyenLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("SoLuongTuyenDung")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenHoKinhDoanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_ViecLam", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangXeCoEntities", b =>
                {
                    b.Property<int>("IdBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiDang"), 1L, 1);

                    b.Property<string>("BienSoXe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("HangXe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MauSac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nam")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("OtoDongXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtoHopSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Oto_HopSo");

                    b.Property<string>("OtoKieuDang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Oto_KieuDang");

                    b.Property<string>("OtoNhieuLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Oto_NhieuLieu");

                    b.Property<byte?>("OtoSocho")
                        .HasColumnType("tinyint")
                        .HasColumnName("Oto_Socho");

                    b.Property<string>("PhuTungXeLoaiPhuTung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuTungXe_LoaiPhuTung");

                    b.Property<bool?>("PhuTungXeMienPhi")
                        .HasColumnType("bit");

                    b.Property<string>("PhuongTienKhacLoaiXeChuyenDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongTienKhacNhienLieu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhuongTienKhac_NhienLieu");

                    b.Property<string>("PhuongTienKhacSoChoXeKhachXeBuyt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SoKmDaDi")
                        .HasColumnType("float");

                    b.Property<string>("XeDapBaoHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("XeDap_BaoHang");

                    b.Property<string>("XeDapChatLuongKhung")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("XeDap_ChatLuongKhung");

                    b.Property<bool?>("XeDapDaSuDung")
                        .HasColumnType("bit")
                        .HasColumnName("XeDap_DaSuDung");

                    b.Property<string>("XeDapKichThuocKhung")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("XeDap_KichThuocKhung");

                    b.Property<string>("XeDapLoaiXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("XeDapMienPhi")
                        .HasColumnType("bit")
                        .HasColumnName("XeDap_MienPhi");

                    b.Property<bool?>("XeDienDaSuDung")
                        .HasColumnType("bit")
                        .HasColumnName("XeDien_DaSuDung");

                    b.Property<string>("XeDienDongCo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XeDien_DongCo");

                    b.Property<string>("XeDienLoaiXe")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("XeDien_LoaiXe");

                    b.Property<bool?>("XeDienMienPhi")
                        .HasColumnType("bit")
                        .HasColumnName("XeDien_MienPhi");

                    b.Property<string>("XeMayDongXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeMayDungtich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XeMay_Dungtich");

                    b.Property<string>("XeMayLoaiXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeTaiNhieuLieu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("XeTai_NhieuLieu");

                    b.Property<string>("XeTaiTrongTai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("XeTai_TrongTai");

                    b.Property<string>("XeTaiXuatXu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XeTai_XuatXu");

                    b.Property<string>("Xuatxu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBaiDang");

                    b.ToTable("BaiDang_XeCo", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_DanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhMuc"), 1L, 1);

                    b.Property<int?>("IdDanhMucCha")
                        .HasColumnType("int")
                        .HasColumnName("id_DanhMucCha");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_DanhMuc");

                    b.HasKey("IdDanhMuc");

                    b.HasIndex("IdDanhMucCha");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.GiaoDichDatCoc", b =>
                {
                    b.Property<int>("IdDatCoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDatCoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatCoc"), 1L, 1);

                    b.Property<bool?>("GiaoDichThanhCong")
                        .HasColumnType("bit")
                        .HasColumnName("giaoDichThanhCong");

                    b.Property<bool?>("HuyGiaoDich")
                        .HasColumnType("bit")
                        .HasColumnName("huyGiaoDich");

                    b.Property<string>("SdtBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sdtBan");

                    b.Property<string>("SdtMua")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sdtMua");

                    b.Property<double?>("SoTienDatCoc")
                        .HasColumnType("float");

                    b.HasKey("IdDatCoc");

                    b.HasIndex("SdtBan");

                    b.HasIndex("SdtMua");

                    b.ToTable("GiaoDich_DatCoc", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.HinhAnhBaiDangEntities", b =>
                {
                    b.Property<int>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_HinhAnh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHinhAnh"), 1L, 1);

                    b.Property<string>("IdMediaCloud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("idMediaCloud");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("id_SanPham");

                    b.Property<bool?>("VideoType")
                        .HasColumnType("bit")
                        .HasColumnName("videoType");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdSanPham");

                    b.ToTable("HinhAnh_BaiDang", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.NguoiDungEntities", b =>
                {
                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("HinhCmnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Hinh_CMND");

                    b.Property<byte?>("LoaiDichVu")
                        .HasColumnType("tinyint")
                        .HasColumnName("Loai_DichVu");

                    b.Property<string>("MsdkDoanhNghiep")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("MSDK_DoanhNghiep")
                        .IsFixedLength();

                    b.Property<DateTime?>("NgayKetThucDichVu")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayKetThuc_DichVu");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("passwordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("passwordSalt");

                    b.Property<string>("SoCmnd")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)")
                        .HasColumnName("So_CMND")
                        .IsFixedLength();

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.HasKey("SoDienThoai");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.ThuocTinhDanhMuc", b =>
                {
                    b.Property<int>("IdThuocTinh")
                        .HasColumnType("int")
                        .HasColumnName("id_ThuocTinh");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("id_DanhMuc");

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_ThuocTinh");

                    b.HasKey("IdThuocTinh");

                    b.ToTable("ThuocTinh_DanhMuc", (string)null);
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangEntities", b =>
                {
                    b.HasOne("STU.LVTN.SERVER.Model.DanhMuc", "IdDanhMucConNavigation")
                        .WithMany("BaiDangs")
                        .HasForeignKey("IdDanhMucCon")
                        .HasConstraintName("FK_BaiDang_DanhMuc");

                    b.HasOne("STU.LVTN.SERVER.Model.NguoiDungEntities", "SdtNguoiBanNavigation")
                        .WithMany("BaiDangs")
                        .HasForeignKey("SdtNguoiBan")
                        .HasConstraintName("FK_BaiDang_NguoiDung");

                    b.Navigation("IdDanhMucConNavigation");

                    b.Navigation("SdtNguoiBanNavigation");
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.DanhMuc", b =>
                {
                    b.HasOne("STU.LVTN.SERVER.Model.DanhMuc", "IdDanhMucChaNavigation")
                        .WithMany("InverseIdDanhMucChaNavigation")
                        .HasForeignKey("IdDanhMucCha")
                        .HasConstraintName("FK_DanhMuc_DanhMuc");

                    b.Navigation("IdDanhMucChaNavigation");
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.GiaoDichDatCoc", b =>
                {
                    b.HasOne("STU.LVTN.SERVER.Model.NguoiDungEntities", "SdtBanNavigation")
                        .WithMany("GiaoDichDatCocSdtBanNavigations")
                        .HasForeignKey("SdtBan")
                        .HasConstraintName("FK_GiaoDich_DatCoc_NguoiDung");

                    b.HasOne("STU.LVTN.SERVER.Model.NguoiDungEntities", "SdtMuaNavigation")
                        .WithMany("GiaoDichDatCocSdtMuaNavigations")
                        .HasForeignKey("SdtMua")
                        .HasConstraintName("FK_GiaoDich_DatCoc_NguoiDung1");

                    b.Navigation("SdtBanNavigation");

                    b.Navigation("SdtMuaNavigation");
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.HinhAnhBaiDangEntities", b =>
                {
                    b.HasOne("STU.LVTN.SERVER.Model.BaiDangEntities", "IdSanPhamNavigation")
                        .WithMany("HinhAnhBaiDangs")
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_HinhAnh_BaiDang_BaiDang");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.BaiDangEntities", b =>
                {
                    b.Navigation("HinhAnhBaiDangs");
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.DanhMuc", b =>
                {
                    b.Navigation("BaiDangs");

                    b.Navigation("InverseIdDanhMucChaNavigation");
                });

            modelBuilder.Entity("STU.LVTN.SERVER.Model.NguoiDungEntities", b =>
                {
                    b.Navigation("BaiDangs");

                    b.Navigation("GiaoDichDatCocSdtBanNavigations");

                    b.Navigation("GiaoDichDatCocSdtMuaNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
