const listCategoryFilterParams = [
    // Chung cư
    {
        categoryId: 1,
        subCategoryId: 13,
        filterParams: [
            {
                key: 'ban',
                label: 'Mong muốn',
                type: 'array',
                data: [
                    { value: 'Bán', text: 'Bán' },
                    { value: 'Cho thuê', text: 'Cho thuê' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'dienTich',
                label: 'Diện tích',
                type: 'number',
                min: 0,
                max: 1000,
                unit: 'm²',
            },
            {
                key: 'loaiHinh',
                label: 'Loại hình chung cư',
                type: 'multiChoice',
                data: [
                    { value: 'Chung cư', text: 'Chung cư' },
                    { value: 'Duplex', text: 'Duplex' },
                    { value: 'PentHouse', text: 'PentHouse' },
                    {
                        value: 'Căn hộ dịch vụ, mini',
                        text: 'Căn hộ dịch vụ, mini',
                    },
                    { value: 'Tập thể, cư xá', text: 'Tập thể, cư xá' },
                    { value: 'Officetel', text: 'Officetel' },
                ],
            },
            {
                key: 'soPhongNgu',
                label: 'Số phòng ngủ',
                type: 'array',
                data: [
                    { value: '1', text: '1' },
                    { value: '2', text: '2' },
                    { value: '3', text: '3' },
                    { value: '4', text: '4' },
                    { value: '5', text: '5' },
                    { value: '6', text: '6' },
                    { value: '7', text: '7' },
                    { value: '8', text: '8' },
                    { value: '9', text: '9' },
                    { value: '10', text: '10' },
                    { value: 'trên 10', text: 'trên 10' },
                ],
                unit: 'phòng ngủ',
            },
            {
                key: 'soToilet',
                label: 'Số phòng vệ sinh',
                type: 'array',
                data: [
                    { value: '1', text: '1' },
                    { value: '2', text: '2' },
                    { value: '3', text: '3' },
                    { value: '4', text: '4' },
                    { value: '5', text: '5' },
                    { value: '6', text: '6' },
                    { value: '7', text: '7' },
                    { value: '8', text: '8' },
                    { value: '9', text: '9' },
                    { value: '10', text: '10' },
                    { value: 'trên 10', text: 'trên 10' },
                ],
                unit: 'toilet',
            },
            {
                key: 'huongBanCong',
                label: 'Hướng ban công',
                type: 'array',
                data: [
                    { value: 'Đông', text: 'Đông' },
                    { value: 'Tây', text: 'Tây' },
                    { value: 'Nam', text: 'Nam' },
                    { value: 'Bắc', text: 'Bắc' },
                    { value: 'Đông Bắc', text: 'Đông Bắc' },
                    { value: 'Đông Nam', text: 'Đông Nam' },
                    { value: 'Tây Bắc', text: 'Tây Bắc' },
                    { value: 'Tây Nam', text: 'Tây Nam' },
                ],
            },
            {
                key: 'huongCuaChinh',
                label: 'Hướng cửa chính',
                type: 'array',
                data: [
                    { value: 'Đông', text: 'Đông' },
                    { value: 'Tây', text: 'Tây' },
                    { value: 'Nam', text: 'Nam' },
                    { value: 'Bắc', text: 'Bắc' },
                    { value: 'Đông Bắc', text: 'Đông Bắc' },
                    { value: 'Đông Nam', text: 'Đông Nam' },
                    { value: 'Tây Bắc', text: 'Tây Bắc' },
                    { value: 'Tây Nam', text: 'Tây Nam' },
                ],
            },
            {
                key: 'tinhTrangNoiThat',
                label: 'Tình trạng nội thất',
                type: 'array',
                data: [
                    { value: 'Bàn giao thô', text: 'Bàn giao thô' },
                    { value: 'Nội thất cơ bản', text: 'Nội thất cơ bản' },
                    { value: 'Nội thất đầy dủ', text: 'Nội thất đầy dủ' },
                    {
                        value: 'Nội thất sang trọng',
                        text: 'Nội thất sang trọng',
                    },
                ],
            },
            {
                key: 'banGiao',
                label: 'Bàn giao',
                type: 'array',
                data: [
                    { value: 'Đã bàn giao', text: 'Đã bàn giao' },
                    { value: 'Chưa bàn giao', text: 'Chưa bàn giao' },
                ],
            },
            {
                key: 'giayToPhapLy',
                label: 'Giấy tờ pháp lý',
                type: 'array',
                data: [
                    { value: 'Đã có sổ', text: 'Đã có sổ' },
                    { value: 'Chưa có sổ', text: 'Chưa có sổ' },
                    { value: 'Giấy tờ khác', text: 'Giấy tờ khác' },
                ],
            },
        ],
    },
    // Nhà
    {
        categoryId: 1,
        subCategoryId: 14,
        filterParams: [
            {
                key: 'ban',
                label: 'Mong muốn',
                type: 'array',
                data: [
                    { value: true, text: 'Bán' },
                    { value: false, text: 'Cho thuê' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'dienTich',
                label: 'Diện tích',
                type: 'number',
                min: 0,
                max: 1000,
                unit: 'm²',
            },
            {
                key: 'loaiHinh',
                label: 'Loại hình nhà ở',
                type: 'array',
                data: [
                    {
                        value: 'Nhà mặt phố, mặt tiền',
                        text: 'Nhà mặt phố, mặt tiền',
                    },
                    { value: 'Nhà ngỏ, hẻm', text: 'Nhà ngỏ, hẻm' },
                    { value: 'Nhà biệt thự', text: 'Nhà biệt thự' },
                    { value: 'Nhà phố liền kề', text: 'Nhà phố liền kề' },
                ],
            },
            {
                key: 'soPhongNgu',
                label: 'Số phòng ngủ',
                type: 'array',
                data: [
                    { value: '1', text: '1' },
                    { value: '2', text: '2' },
                    { value: '3', text: '3' },
                    { value: '4', text: '4' },
                    { value: '5', text: '5' },
                    { value: '6', text: '6' },
                    { value: '7', text: '7' },
                    { value: '8', text: '8' },
                    { value: '9', text: '9' },
                    { value: '10', text: '10' },
                    { value: 'trên 10', text: 'trên 10' },
                ],
                unit: 'phòng ngủ',
            },
            {
                key: 'soToilet',
                label: 'Số phòng vệ sinh',
                type: 'array',
                data: [
                    { value: '1', text: '1' },
                    { value: '2', text: '2' },
                    { value: '3', text: '3' },
                    { value: '4', text: '4' },
                    { value: '5', text: '5' },
                    { value: '6', text: '6' },
                    { value: '7', text: '7' },
                    { value: '8', text: '8' },
                    { value: '9', text: '9' },
                    { value: '10', text: '10' },
                    { value: 'trên 10', text: 'trên 10' },
                ],
                unit: 'toilet',
            },

            {
                key: 'huongCuaChinh',
                label: 'Hướng cửa chính',
                type: 'array',
                data: [
                    { value: 'Đông', text: 'Đông' },
                    { value: 'Tây', text: 'Tây' },
                    { value: 'Nam', text: 'Nam' },
                    { value: 'Bắc', text: 'Bắc' },
                    { value: 'Đông Bắc', text: 'Đông Bắc' },
                    { value: 'Đông Nam', text: 'Đông Nam' },
                    { value: 'Tây Bắc', text: 'Tây Bắc' },
                    { value: 'Tây Nam', text: 'Tây Nam' },
                ],
            },
            {
                key: 'tinhTrangNoiThat',
                label: 'Tình trạng nội thất',
                type: 'array',
                data: [
                    { value: 'Bàn giao thô', text: 'Bàn giao thô' },
                    { value: 'Nội thất cơ bản', text: 'Nội thất cơ bản' },
                    { value: 'Nội thất đầy dủ', text: 'Nội thất đầy dủ' },
                    {
                        value: 'Nội thất sang trọng',
                        text: 'Nội thất sang trọng',
                    },
                ],
            },
            {
                key: 'banGiao',
                label: 'Bàn giao',
                type: 'array',
                data: [
                    { value: 'Đã bàn giao', text: 'Đã bàn giao' },
                    { value: 'Chưa bàn giao', text: 'Chưa bàn giao' },
                ],
            },
            {
                key: 'giayToPhapLy',
                label: 'Giấy tờ pháp lý',
                type: 'array',
                data: [
                    { value: 'Đã có sổ', text: 'Đã có sổ' },
                    { value: 'Chưa có sổ', text: 'Chưa có sổ' },
                    { value: 'Giấy tờ khác', text: 'Giấy tờ khác' },
                ],
            },
        ],
    },
    // Đất
    {
        categoryId: 1,
        subCategoryId: 15,
        filterParams: [
            {
                key: 'ban',
                label: 'Mong muốn',
                type: 'array',
                data: [
                    { value: true, text: 'Bán' },
                    { value: false, text: 'Cho thuê' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'dienTich',
                label: 'Diện tích',
                type: 'number',
                min: 0,
                max: 1000,
                unit: 'm²',
            },
            {
                key: 'loaiHinh',
                label: 'Loại hình đất',
                type: 'array',
                data: [
                    {
                        value: 'Đất thổ cư',
                        text: 'Đất thổ cư',
                    },
                    { value: 'Đất nền dự án', text: 'Đất nền dự án' },
                    { value: 'Đất công nghiệp', text: 'Đất công nghiệp' },
                    { value: 'Đất nông nghiệp', text: 'Đất nông nghiệp' },
                ],
            },
            {
                key: 'huongCuaChinh',
                label: 'Hướng cửa chính',
                type: 'array',
                data: [
                    { value: 'Đông', text: 'Đông' },
                    { value: 'Tây', text: 'Tây' },
                    { value: 'Nam', text: 'Nam' },
                    { value: 'Bắc', text: 'Bắc' },
                    { value: 'Đông Bắc', text: 'Đông Bắc' },
                    { value: 'Đông Nam', text: 'Đông Nam' },
                    { value: 'Tây Bắc', text: 'Tây Bắc' },
                    { value: 'Tây Nam', text: 'Tây Nam' },
                ],
            },
            {
                key: 'dacDiemDat',
                label: 'Đặc điểm đất',
                type: 'array',
                data: [
                    { value: 'Hẻm xe hơi', text: 'Hẻm xe hơi' },
                    { value: 'Mặt tiền', text: 'Mặt tiền' },
                    { value: 'Nở hậu', text: 'Nở hậu' },
                ],
            },
            {
                key: 'banGiao',
                label: 'Bàn giao',
                type: 'array',
                data: [
                    { value: 'Đã bàn giao', text: 'Đã bàn giao' },
                    { value: 'Chưa bàn giao', text: 'Chưa bàn giao' },
                ],
            },
            {
                key: 'giayToPhapLy',
                label: 'Giấy tờ pháp lý',
                type: 'array',
                data: [
                    { value: 'Đã có sổ', text: 'Đã có sổ' },
                    { value: 'Chưa có sổ', text: 'Chưa có sổ' },
                    { value: 'Giấy tờ khác', text: 'Giấy tờ khác' },
                ],
            },
        ],
    },
    // Văn phòng
    {
        categoryId: 1,
        subCategoryId: 16,
        filterParams: [
            {
                key: 'ban',
                label: 'Mong muốn',
                type: 'array',
                data: [
                    { value: true, text: 'Bán' },
                    { value: false, text: 'Cho thuê' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'dienTich',
                label: 'Diện tích',
                type: 'number',
                min: 0,
                max: 1000,
                unit: 'm²',
            },
            {
                key: 'loaiHinh',
                label: 'Loại hình văn phòng',
                type: 'array',
                data: [
                    {
                        value: 'Mặt bằng kinh doanh',
                        text: 'Mặt bằng kinh doanh',
                    },
                    { value: 'Văn phòng', text: 'Văn phòng' },
                    { value: 'Shophouse', text: 'Shophouse' },
                    { value: 'Officetel', text: 'Officetel' },
                ],
            },
            {
                key: 'huongCuaChinh',
                label: 'Hướng cửa chính',
                type: 'array',
                data: [
                    { value: 'Đông', text: 'Đông' },
                    { value: 'Tây', text: 'Tây' },
                    { value: 'Nam', text: 'Nam' },
                    { value: 'Bắc', text: 'Bắc' },
                    { value: 'Đông Bắc', text: 'Đông Bắc' },
                    { value: 'Đông Nam', text: 'Đông Nam' },
                    { value: 'Tây Bắc', text: 'Tây Bắc' },
                    { value: 'Tây Nam', text: 'Tây Nam' },
                ],
            },
            {
                key: 'tinhTrangNoiThat',
                label: 'Tình trạng nội thất',
                type: 'array',
                data: [
                    { value: 'Bàn giao thô', text: 'Bàn giao thô' },
                    { value: 'Nội thất cơ bản', text: 'Nội thất cơ bản' },
                    { value: 'Nội thất đầy dủ', text: 'Nội thất đầy dủ' },
                    {
                        value: 'Nội thất sang trọng',
                        text: 'Nội thất sang trọng',
                    },
                ],
            },
            {
                key: 'banGiao',
                label: 'Bàn giao',
                type: 'array',
                data: [
                    { value: 'Đã bàn giao', text: 'Đã bàn giao' },
                    { value: 'Chưa bàn giao', text: 'Chưa bàn giao' },
                ],
            },
            {
                key: 'giayToPhapLy',
                label: 'Giấy tờ pháp lý',
                type: 'array',
                data: [
                    { value: 'Đã có sổ', text: 'Đã có sổ' },
                    { value: 'Chưa có sổ', text: 'Chưa có sổ' },
                    { value: 'Giấy tờ khác', text: 'Giấy tờ khác' },
                ],
            },
        ],
    },
    // Ô tô
    {
        categoryId: 2,
        subCategoryId: 18,
        filterParams: [
            {
                key: 'hang',
                label: 'Hãng',
                type: 'array',
                data: [
                    { value: 'Toyota' },
                    { value: 'Vinfast ' },
                    { value: 'Huyndai' },
                    { value: 'Ford' },
                    { value: 'Honda' },
                    { value: 'Mitsubishi' },
                    { value: 'Kia' },
                    { value: 'Mazda' },
                    { value: 'Acura' },
                    { value: 'Alfa Romeo' },
                ],
            },

            {
                key: 'nam',
                label: 'Năm sản xuất',
                type: 'array',
                data: [
                    { value: '2022' },
                    { value: '2019' },
                    { value: '2018' },
                    { value: '2017' },
                    { value: '2016' },
                    { value: '2015' },
                    { value: '2014' },
                    { value: '2013' },
                    { value: '2012' },
                    { value: '2011' },
                    { value: '2010' },
                    { value: '2009' },
                    { value: '2008' },
                    { value: '2007' },
                    { value: '2006' },
                    { value: '2005' },
                    { value: '2004' },
                    { value: '2003' },
                    { value: '2002' },
                    { value: '2001' },
                    { value: '2000' },
                    { value: 'Trước năm 2000' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'daSuDung',
                label: 'Tình trạng',
                type: 'array',
                data: [
                    { value: 'true', text: 'Đã sử dụng' },
                    { value: 'false', text: 'Chưa sử dụng' },
                ],
            },
            {
                key: 'nhienLieu',
                label: 'Nhiên liệu',
                type: 'array',
                data: [
                    { value: 'Xăng' },
                    { value: 'Dầu' },
                    { value: 'Hybrid' },
                ],
            },
        ],
    },
    {
        categoryId: 2,
        subCategoryId: 19,
        filterParams: [
            {
                key: 'hang',
                label: 'Hãng',
                type: 'array',
                data: [
                    { value: 'Honda' },
                    { value: 'Suzuki' },
                    { value: 'Toyota' },
                    { value: 'SYM' },
                    { value: 'Yamaha' },
                    { value: 'Kawasaki' },
                    { value: 'Kymco' },
                    { value: 'Vinfast' },
                ],
            },

            {
                key: 'nam',
                label: 'Năm sản xuất',
                type: 'array',
                data: [
                    { value: '2022' },
                    { value: '2019' },
                    { value: '2018' },
                    { value: '2017' },
                    { value: '2016' },
                    { value: '2015' },
                    { value: '2014' },
                    { value: '2013' },
                    { value: '2012' },
                    { value: '2011' },
                    { value: '2010' },
                    { value: '2009' },
                    { value: '2008' },
                    { value: '2007' },
                    { value: '2006' },
                    { value: '2005' },
                    { value: '2004' },
                    { value: '2003' },
                    { value: '2002' },
                    { value: '2001' },
                    { value: '2000' },
                    { value: 'Trước năm 2000' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'daSuDung',
                label: 'Tình trạng',
                type: 'array',
                data: [
                    { value: 'true', text: 'Đã sử dụng' },
                    { value: 'false', text: 'Chưa sử dụng' },
                ],
            },
            {
                key: 'nhienLieu',
                label: 'Nhiên liệu',
                type: 'array',
                data: [
                    { value: 'Xăng' },
                    { value: 'Dầu' },
                    { value: 'Hybrid' },
                ],
            },
            {
                key: 'soKmDaDi',
                label: 'Số Km đã đi',
                type: 'number',
                min: 0,
                max: 500000,
            },
            {
                key: 'loaiXe',
                label: 'Loại Xe',
                type: 'array',
                data: [
                    { value: 'Tay ga' },
                    { value: 'Xe số' },
                    { value: 'Tay côn/Moto' },
                ],
            },
            {
                key: 'dungTichXe',
                label: 'Dung tích xe',
                type: 'array',
                data: [
                    { value: 'Dưới 50cc' },
                    { value: '50 - 100cc' },
                    { value: '100 - 175cc' },
                    { value: 'Trên 175cc' },
                    { value: 'Không biết rõ' },
                ],
            },
        ],
    },
    // xe tải
    {
        categoryId: 2,
        subCategoryId: 20,
        filterParams: [
            {
                key: 'hang',
                label: 'Hãng',
                type: 'array',
                data: [
                    { value: 'Chiến Thắng' },
                    { value: 'Cửu Long' },
                    { value: 'Daewoo' },
                    { value: 'Dongben' },
                    { value: 'Dongfeng' },
                    { value: 'Huyndai' },
                    { value: 'FAW' },
                    { value: 'Fusin' },
                    { value: 'Fuso' },
                    { value: 'Hino' },
                    { value: 'Isuzu' },
                    { value: 'Kia' },
                    { value: 'Mitsubishi' },
                    { value: 'Samco' },
                ],
            },

            {
                key: 'nam',
                label: 'Năm sản xuất',
                type: 'array',
                data: [
                    { value: '2022' },
                    { value: '2019' },
                    { value: '2018' },
                    { value: '2017' },
                    { value: '2016' },
                    { value: '2015' },
                    { value: '2014' },
                    { value: '2013' },
                    { value: '2012' },
                    { value: '2011' },
                    { value: '2010' },
                    { value: '2009' },
                    { value: '2008' },
                    { value: '2007' },
                    { value: '2006' },
                    { value: '2005' },
                    { value: '2004' },
                    { value: '2003' },
                    { value: '2002' },
                    { value: '2001' },
                    { value: '2000' },
                    { value: 'Trước năm 2000' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },

            {
                key: 'nhienLieu',
                label: 'Nhiên liệu',
                type: 'array',
                data: [
                    { value: 'Xăng' },
                    { value: 'Dầu' },
                    { value: 'Hybrid' },
                    { value: 'Điện' },
                ],
            },
            {
                key: 'soKmDaDi',
                label: 'Số Km đã đi',
                type: 'number',
                min: 0,
                max: 500000,
            },
            {
                key: 'trongTai',
                label: 'Trọng tải',
                type: 'array',
                data: [
                    { value: '<1 tấn' },
                    { value: '2 tấn' },
                    { value: '4 tấn' },
                    { value: '5 tấn' },
                    { value: '6 tấn' },
                    { value: '7 tấn' },
                    { value: '8 tấn' },
                    { value: '9 tấn' },
                    { value: '10 tấn' },
                    { value: '11 tấn' },
                    { value: '12 tấn' },
                    { value: '13 tấn' },
                    { value: '>13 tấn' },
                ],
            },
        ],
    },
    // Xe điện
    {
        categoryId: 2,
        subCategoryId: 21,
        filterParams: [
            {
                key: 'hang',
                label: 'Hãng',
                type: 'array',
                data: [
                    { value: 'Aima' },
                    { value: 'Anbico' },
                    { value: 'Asama' },
                    { value: 'BMX' },
                    { value: 'Bridgestone' },
                    { value: 'Detech' },
                    { value: 'Dibao' },
                    { value: 'Vinfast' },
                    { value: 'DKBike' },
                    { value: 'Honda' },
                    { value: 'Jett' },
                    { value: 'Kingda' },
                    { value: 'MBI' },
                ],
            },

            {
                key: 'nam',
                label: 'Năm sản xuất',
                type: 'array',
                data: [
                    { value: '2022' },
                    { value: '2019' },
                    { value: '2018' },
                    { value: '2017' },
                    { value: '2016' },
                    { value: '2015' },
                    { value: '2014' },
                    { value: '2013' },
                    { value: '2012' },
                    { value: '2011' },
                    { value: '2010' },
                    { value: '2009' },
                    { value: '2008' },
                    { value: '2007' },
                    { value: '2006' },
                    { value: '2005' },
                    { value: '2004' },
                    { value: '2003' },
                    { value: '2002' },
                    { value: '2001' },
                    { value: '2000' },
                    { value: 'Trước năm 2000' },
                ],
            },
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'daSuDung',
                label: 'Tình trạng',
                type: 'array',
                data: [
                    { value: 'true', text: 'Đã sử dụng' },
                    { value: 'false', text: 'Chưa sử dụng' },
                ],
            },
            {
                key: 'dongCo',
                label: 'Động cơ',
                type: 'array',
                data: [
                    { value: '< 200W' },
                    { value: '200 - 250W' },
                    { value: '251 - 350W' },
                    { value: '351 - 500W' },
                    { value: '501 - 1000W' },
                    { value: '>1000W' },
                ],
            },

            {
                key: 'baoHanh',
                label: 'Bảo Hành',
                type: 'array',
                data: [
                    { value: 'true', text: 'Còn bảo hành' },
                    { value: 'false', text: 'Hết bảo hành' },
                ],
            },
            {
                key: 'loaiXe',
                label: 'Loại Xe',
                type: 'array',
                data: [
                    { value: 'Xe đạp điện' },
                    { value: 'Xe máy điện' },
                    { value: 'Xe điện khác' },
                ],
            },
        ],
    },
    // Xe đạp
    {
        categoryId: 2,
        subCategoryId: 22,
        filterParams: [
            {
                key: 'hang',
                label: 'Hãng',
                type: 'array',
                data: [
                    { value: 'Aima' },
                    { value: 'Anbico' },
                    { value: 'Asama' },
                    { value: 'BMX' },
                    { value: 'Bridgestone' },
                    { value: 'Detech' },
                    { value: 'Dibao' },
                    { value: 'Vinfast' },
                    { value: 'DKBike' },
                    { value: 'Honda' },
                    { value: 'Jett' },
                    { value: 'Kingda' },
                    { value: 'MBI' },
                ],
            },

            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'daSuDung',
                label: 'Tình trạng',
                type: 'array',
                data: [
                    { value: 'true', text: 'Đã sử dụng' },
                    { value: 'false', text: 'Chưa sử dụng' },
                ],
            },

            {
                key: 'baoHanh',
                label: 'Bảo Hành',
                type: 'array',
                data: [
                    { value: 'true', text: 'Còn bảo hành' },
                    { value: 'false', text: 'Hết bảo hành' },
                ],
            },
            {
                key: 'loaiXe',
                label: 'Loại Xe',
                type: 'array',
                data: [
                    { value: 'Xe đạp phổ thông' },
                    { value: 'Xe đạp thể thao' },
                    { value: 'Xe đạp trẻ em' },
                    { value: 'Xe đạp khác' },
                ],
            },
            {
                key: 'xuatXu',
                label: 'Xuất xứ',
                type: 'array',
                data: [
                    { value: 'Việt Nam' },
                    { value: 'Ấn Độ' },
                    { value: 'Thái Lan' },
                    { value: 'Hàn Quốc' },
                    { value: 'Nhật Bản' },
                    { value: 'Trung Quốc' },
                    { value: 'Mỹ' },
                    { value: 'Đức' },
                    { value: 'Đài Loan' },
                ],
            },
            {
                key: 'chatLieuKhung',
                label: 'Chất liệu khung',
                type: 'array',
                data: [
                    { value: 'Thép' },
                    { value: 'Carbon' },
                    { value: 'Inox' },
                    { value: 'Nhôm' },
                    { value: 'Sắt' },
                    { value: 'Titanium' },
                ],
            },
            {
                key: 'kichThuocKhung',
                label: 'Kích thước khung',
                type: 'array',
                data: [
                    { value: 'XS (43cm)' },
                    { value: 'S (46.5 cm)' },
                    { value: 'M (50 cm)' },
                    { value: 'L (55.5 cm)' },
                    { value: 'XL (58.5 cm)' },
                ],
            },
        ],
    },
    // Xe khác
    {
        categoryId: 2,
        subCategoryId: 23,
        filterParams: [
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000000,
            },
            {
                key: 'daSuDung',
                label: 'Tình trạng',
                type: 'array',
                data: [
                    { value: 'true', text: 'Đã sử dụng' },
                    { value: 'false', text: 'Chưa sử dụng' },
                ],
            },
            {
                key: 'nam',
                label: 'Năm sản xuất',
                type: 'array',
                data: [
                    { value: '2022' },
                    { value: '2019' },
                    { value: '2018' },
                    { value: '2017' },
                    { value: '2016' },
                    { value: '2015' },
                    { value: '2014' },
                    { value: '2013' },
                    { value: '2012' },
                    { value: '2011' },
                    { value: '2010' },
                    { value: '2009' },
                    { value: '2008' },
                    { value: '2007' },
                    { value: '2006' },
                    { value: '2005' },
                    { value: '2004' },
                    { value: '2003' },
                    { value: '2002' },
                    { value: '2001' },
                    { value: '2000' },
                    { value: 'Trước năm 2000' },
                ],
            },
            {
                key: 'soKmDaDi',
                label: 'Số Km đã đi',
                type: 'number',
                min: 0,
                max: 500000,
            },

            {
                key: 'loaiXe',
                label: 'Loại Xe',
                type: 'array',
                data: [
                    { value: 'Xe đạp phổ thông' },
                    { value: 'Xe đạp thể thao' },
                    { value: 'Xe đạp trẻ em' },
                    { value: 'Xe đạp khác' },
                ],
            },
            {
                key: 'xuatXu',
                label: 'Xuất xứ',
                type: 'array',
                data: [
                    { value: 'Việt Nam' },
                    { value: 'Ấn Độ' },
                    { value: 'Thái Lan' },
                    { value: 'Hàn Quốc' },
                    { value: 'Nhật Bản' },
                    { value: 'Trung Quốc' },
                    { value: 'Mỹ' },
                    { value: 'Đức' },
                    { value: 'Đài Loan' },
                ],
            },
            {
                key: 'nhienLieu',
                label: 'Nhiên liệu',
                type: 'array',
                data: [
                    { value: 'Xăng' },
                    { value: 'Dầu' },
                    { value: 'Hybrid' },
                ],
            },
        ],
    },
    // Phụ tùng
    {
        categoryId: 2,
        subCategoryId: 24,
        filterParams: [
            {
                key: 'gia',
                label: 'Giá',
                type: 'number',
                min: 0,
                max: 30000000,
            },
            {
                key: 'loaiPhuTung',
                label: 'Loại phụ tùng',
                type: 'array',
                data: [
                    { value: 'Phụ tùng xe máy' },
                    { value: 'Phụ tùng xe đạp' },
                    { value: 'Phụ tùng ô tô' },
                    { value: 'Phụ tùng xe tải/ xe ben' },
                    { value: 'Phụ tùng xe điện' },
                ],
            },
        ],
    },
]

export const getFilterParams = (categoryId, subCategoryId) => {
    const findResult = listCategoryFilterParams.find(
        item =>
            item.categoryId === categoryId &&
            item.subCategoryId === subCategoryId
    )

    return findResult ? findResult.filterParams : []
}
